import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/components/Navigation/Header";
import "@/styles/global.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <Header />
        <div className="global-padding">
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
